"""Every cap of the per-app knowledge subsystem, in one place.

Each constant has a row in ``tests/mobile/bounds_rows/stream_ak1.py`` (ceiling
plus the constraint that decides it). Other knowledge modules read these as
``knowledge_limits.NAME``; none declares a cap of its own.
"""

from __future__ import annotations

#: Rows kept per learned table, history included (supersede never deletes).
MAX_ROWS = {
    "lessons": 500,
    "shortcuts": 100,
    "elements": 2000,
    "screens": 500,
    "edges": 3000,
    "timings": 3000,
    "popups": 100,
    "mistakes": 300,
    "runs": 500,
}
#: The biggest per-table cap, for the single scalar CEILINGS row.
MAX_ROWS_LARGEST = max(MAX_ROWS.values())

MAX_RUNS_PER_ITEM = 20
SAMPLES_PER_TIMING = 30
MAX_ANCHORS = 40
REMAP_MIN_JACCARD = 0.6
ENV_ENTRIES = 8
PRECONDITION_STEPS = 5
MAX_KBUF = 500
#: Feedback event rows kept per app; the oldest go first.
MAX_FEEDBACK_EVENTS = 2000
#: Refused-write event rows kept per app; the oldest go first.
MAX_REFUSED_EVENTS = 2000
SNAPSHOT_MAX_ROWS = 4000
STABLE_BLOCK_CHARS = 6000
STABLE_BLOCK_TOKENS = 1500
MAX_TURN_RULES = 3
RULE_CHARS = 200
MAX_CACHED_RUNS = 16
PENDING_RESUME_LIMIT = 3
STALE_RUN_S = 900
LEARN_MAX_STEPS = 500
MIN_SAMPLES_WAIT = 5
WAIT_P90_MARGIN = 1.2
ADAPT_WAIT_FLOOR_MS = 200
POPUP_MIN_RUNS = 3
SHORTCUT_MIN_LEN = 3
SHORTCUT_MAX_LEN = 8
SHORTCUT_MIN_RUNS = 3
GATE_MIN_RUNS = 3
MISTAKE_ACTIVE_RUNS = 2
CONTRADICT_FLOOR = 2
HALF_WEIGHT = 0.5
STALE_AFTER_FAILS = 3
STALE_RETENTION = 0.2
RETENTION_DECAY = 0.9
MAX_FEEDBACK_ITEMS = 3
FEEDBACK_CHARS = 300
REFLECT_MAX_STEPS = 12
REFLECT_MAX_LESSONS = 20
REFLECT_PACKET_CHARS = 12000
REFLECT_MAX_OPS = 8
REFLECT_PENDING_MAX = 10
PAYLOAD_CHARS = 100000
EXPORT_MAX_ROWS = 5000
IMPORT_MAX_ROWS = 2000
LIST_PAGE_ROWS = 25
HEAL_MIN_SCORE = 0.75
HEAL_MAX_CANDIDATES = 40
LOCATOR_QUEUE_MAX = 5
RETENTION_DAYS = 90

#: Every scalar limit by name: what ``qa_mobile_knowledge`` can show, and the
#: reader the bounds sweep sees for constants a later stage consumes.
CONSTANTS = {
    "MAX_ROWS_LARGEST": MAX_ROWS_LARGEST,
    "MAX_RUNS_PER_ITEM": MAX_RUNS_PER_ITEM,
    "SAMPLES_PER_TIMING": SAMPLES_PER_TIMING,
    "MAX_ANCHORS": MAX_ANCHORS,
    "REMAP_MIN_JACCARD": REMAP_MIN_JACCARD,
    "ENV_ENTRIES": ENV_ENTRIES,
    "PRECONDITION_STEPS": PRECONDITION_STEPS,
    "MAX_KBUF": MAX_KBUF,
    "MAX_FEEDBACK_EVENTS": MAX_FEEDBACK_EVENTS,
    "MAX_REFUSED_EVENTS": MAX_REFUSED_EVENTS,
    "SNAPSHOT_MAX_ROWS": SNAPSHOT_MAX_ROWS,
    "STABLE_BLOCK_CHARS": STABLE_BLOCK_CHARS,
    "STABLE_BLOCK_TOKENS": STABLE_BLOCK_TOKENS,
    "MAX_TURN_RULES": MAX_TURN_RULES,
    "RULE_CHARS": RULE_CHARS,
    "MAX_CACHED_RUNS": MAX_CACHED_RUNS,
    "PENDING_RESUME_LIMIT": PENDING_RESUME_LIMIT,
    "STALE_RUN_S": STALE_RUN_S,
    "LEARN_MAX_STEPS": LEARN_MAX_STEPS,
    "MIN_SAMPLES_WAIT": MIN_SAMPLES_WAIT,
    "WAIT_P90_MARGIN": WAIT_P90_MARGIN,
    "ADAPT_WAIT_FLOOR_MS": ADAPT_WAIT_FLOOR_MS,
    "POPUP_MIN_RUNS": POPUP_MIN_RUNS,
    "SHORTCUT_MIN_LEN": SHORTCUT_MIN_LEN,
    "SHORTCUT_MAX_LEN": SHORTCUT_MAX_LEN,
    "SHORTCUT_MIN_RUNS": SHORTCUT_MIN_RUNS,
    "GATE_MIN_RUNS": GATE_MIN_RUNS,
    "MISTAKE_ACTIVE_RUNS": MISTAKE_ACTIVE_RUNS,
    "CONTRADICT_FLOOR": CONTRADICT_FLOOR,
    "HALF_WEIGHT": HALF_WEIGHT,
    "STALE_AFTER_FAILS": STALE_AFTER_FAILS,
    "STALE_RETENTION": STALE_RETENTION,
    "RETENTION_DECAY": RETENTION_DECAY,
    "MAX_FEEDBACK_ITEMS": MAX_FEEDBACK_ITEMS,
    "FEEDBACK_CHARS": FEEDBACK_CHARS,
    "REFLECT_MAX_STEPS": REFLECT_MAX_STEPS,
    "REFLECT_MAX_LESSONS": REFLECT_MAX_LESSONS,
    "REFLECT_PACKET_CHARS": REFLECT_PACKET_CHARS,
    "REFLECT_MAX_OPS": REFLECT_MAX_OPS,
    "REFLECT_PENDING_MAX": REFLECT_PENDING_MAX,
    "PAYLOAD_CHARS": PAYLOAD_CHARS,
    "EXPORT_MAX_ROWS": EXPORT_MAX_ROWS,
    "IMPORT_MAX_ROWS": IMPORT_MAX_ROWS,
    "LIST_PAGE_ROWS": LIST_PAGE_ROWS,
    "HEAL_MIN_SCORE": HEAL_MIN_SCORE,
    "HEAL_MAX_CANDIDATES": HEAL_MAX_CANDIDATES,
    "LOCATOR_QUEUE_MAX": LOCATOR_QUEUE_MAX,
    "RETENTION_DAYS": RETENTION_DAYS,
}
